### ISSUE TITLE
Dependency not found

### ISSUE THREAD

**Issue by giddel** [melo/docker-perl-carton-base#2]
Starting my docker image results in missing dependency:
`Can't locate Params/Util.pm in @INC (you may need to install the Params::Util module) (@INC contains: /deps/local/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /deps/local/lib/perl5/Data/OptList.pm line 7.
 `

Params::Util is installed in the image, but under /deps/local/lib/perl5/x86_64-linux-gnu which is not in @INC.

Any idea?

**Comment by TweakM** [comment]
I had the same problem. It was solved using the following Dockerfile:
```
FROM melopt/perl-carton-base
COPY  . /app
WORKDIR /app
USER root
RUN chown -R app:app /app
USER app
CMD ["perl","./script.pl"]
```

**Comment by melo** [comment]
Sorry, I didn't see this here... I no longer maintain this image, I'll probably remove it.

Currently, all my Perl projects use this image: https://hub.docker.com/r/melopt/perl-alt
